### PR TITLE
Updated the README_Python.md

### PR DESCRIPTION
**Pull request by Maki0806**
The README_Python.md was updated by adding some descriptions of what I implemented. Especially, the filtering demo that was very similar to Matlab one was indicated in this README_Python.md. I would like @rukumagai  to confirm the demo I made, and please give me any comments if you have a question.

### CODE REVIEW

**Comment by Maki0806** [comment]
I have two questions about the design filter of Matlab code.

1. Is the filter setting `[0.1, 0.5]` alright?
    ```matlab
    g = gsp_design_smooth_indicator(G,0.1,0.5);
    ```
    If I used these settings in my Python code, I got the following figure:
    

    If there is no problem of the settings, my implementation of `gsp_design_smooth_indicator` is insufficient...

2. Why did you use `279` for computing MSE?

    ```matlab
    default_mse = sqrt(sum((signal-noizy_signal).^2))/279;
    filtered_mse = sqrt(sum((signal-x).^2))/279;
    ```

    Firstly, I used the length of `data` instead of `279`, but the MSE of that setting was not close to your MSE values. This is because that length is much larger than `279`. Please tell me about that.

**Comment by rukumagai** [comment]
@Maki0806 
Thank you very much for your great cooperation!
Your Python demo is quite close to what I made for Matlab.
I will answer your questions first.

> Is the filter setting `[0.1, 0.5]` alright?

It is alright. My interpretation for `gsp_design_smooth_indicator(G, a1, a2);` is as follows:
When `0 <= x < a1`, it returns `1`.
When `a1 <= x < a2`, it returns value through the function.
When `x >= a2`, it returns `0`.
Thus, your code is better modified as follows:

```
def gsp_design_smooth_indicator(G, a1, a2):
    G.compute_fourier_basis()
    lmax = G.lmax
    fx = lambda x, a: np.exp(-a / x) * (x >= 0)
    gx = lambda x, a: fx(x, a) / (fx(x, a) + fx(1 - x, a))
    # ffin = lambda x, a1, a2: gx(1 - (x - a1) / (a2 - a1), 1) * (x >= a1)
    ffin = lambda x, a1, a2: np.where(
        x >= a1, 
        gx(1 - (x - a1) / (a2 - a1), 1),
        np.where(x >= 0, 1, 0)
    )
    g = lambda x: ffin(x / lmax, a1, a2)
    return filters.Filter(G, g)
```

> Why did you use `279` for computing MSE?

Thank you for pointing this out! I should replace this with the length of `data`.



From here, I describe what I find.
When I ran your demo, the graph signals drawn in Matlab and Python were quite different.
After all, the networkx caused this.

When you run 
```
nx.draw_networkx_nodesnx.draw_networkx_nodes(
            G=graphD,
            pos=position_dict,
            node_color=use_node_values,
            cmap="turbo",
            node_size=node_sizes,
        )
```
 ,  `node_list` is None, so the index of nodes is assigned in the order they appeared on edgelist `graphD`.
Therefore, the original node number `n` is used to call the data of the `n`th node that appeared in the edgelist.

To solve this problem, we define the nodelist as follows:
```
nx.draw_networkx_nodes(
            G=graphD,
            nodelist=np.arange(len(position_dict)),
            pos=position_dict,
            node_color=use_node_values,
            cmap="turbo",
            node_size=node_sizes,
        )
```


Your code is so great that I would like to use it with some modification!
I'm sorry for the delay, I was working to resolve this problem.
Please give me any comments if you have a question!!

**Comment by Maki0806** [comment]
@rukumagai Thank you for your modification. I fully understand my mistakes!

**Comment by rukumagai** [comment]
@Maki0806 Thank you, too! I've just pushed the modified version. Please let me know if there's anything wrong.

**Pull request merged**
